build: off


init:
- cmd: ECHO Starting ZUT.PokerPlanning app building
- cmd: dir

install:
- ps: Install-Product node $env:nodejs_version
- npm install ./ZUT-PokerPlanningClient
- npm install -g @angular/cli
  
test_script:
- node --version
- npm --version
- ng --version
- cd ./ZUT-PokerPlanningClient
- ng build 
- npm start
  
  
