build: off


init:
- cmd: ECHO Starting ZUT.PokerPlanning app building
- cmd: dir

install:
- ps: Install-Product node $env:nodejs_version
- npm install
- npm install -g @angular/cli
  
test_script:
- node --version
- npm --version
- ng --version
- ng build
- npm start --prefix ./ZUT-PokerPlanningClient
  
  
